name: 'Go Vulnerability Check'
description: 'Run govulncheck and annotate vulnerable dependencies and code'
author: 'Your Name'

inputs:
  working-directory:
    description: 'Directory or directories to run govulncheck in. Supports comma-separated or space-delimited paths (e.g., "dir1,dir2" or "dir1 dir2"). Duplicates are filtered, and non-existent directories are skipped with a warning.'
    required: false
    default: '.'

outputs:
  vulnerabilities-found:
    description: 'Whether vulnerabilities were found'
  vulnerability-count:
    description: 'Number of vulnerabilities found'

runs:
  using: 'node20'
  main: 'dist/index.js'
