name: Example Vulnerability Check
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  example:
    name: Check Example for Vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      
      - name: Run govulncheck on example
        id: govulncheck
        uses: ./
        with:
          working-directory: './example'
      
      # Note: We don't fail the workflow here since the example is intentionally vulnerable
      - name: Demonstrate conditional failure
        run: |
          echo "In a real workflow, you might want to fail if vulnerabilities are found:"
          echo "if: steps.govulncheck.outputs.vulnerabilities-found == 'true'"
          echo "run: exit 1"
