name: Malcontent Analysis

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  malcontent:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@b9e0990d219a03df7633c93f6f005a8fecbcab22 # v5.0.1
        with:
          fetch-depth: 0  # Fetch all history for proper diff analysis

      - name: Run Malcontent Analysis
        id: malcontent
        uses: chainguard-dev/malcontent-action@053384afe0bb069ba7e2996bd8c0863731406002 # v0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # NB: Could also set `fail-on-increase: false` and use `if: ${{steps.malcontent.outputs.risk-delta > 5}}` to allow some risk increase

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@ff2f1c621b7f889edc0d3c761ac2e6a3f8cdb0dd #v3.29.0 - 11 Jun 2025
        if: always() # Upload even if the malcontent check fails
        with:
          sarif_file: ${{ steps.malcontent.outputs.sarif-file }}
          category: malcontent
